"""QMetry REST API adapter."""
from __future__ import annotations

from uuid import UUID

import httpx
import structlog

from aita.domain.exceptions import QMetryError
from aita.domain.models import TestResult
from aita.ports.outbound.qmetry_port import QMetryPort

logger = structlog.get_logger()

_STATUS_MAP = {
    "passed": "Pass",
    "failed": "Fail",
    "error": "Fail",
    "skipped": "Skip",
}


class QMetryAdapter(QMetryPort):
    def __init__(self, base_url: str, api_key: str, project_key: str) -> None:
        self._base = base_url.rstrip("/")
        self._key = api_key
        self._project = project_key
        self._headers = {"apiKey": api_key, "Content-Type": "application/json"}

    async def push_results(self, run_id: UUID, results: list[TestResult]) -> str:
        cycle_key = await self.create_test_cycle(f"AITA Run {run_id}", "")
        payload = {
            "cycleKey": cycle_key,
            "testResults": [
                {
                    "testCaseKey": str(r.test_case_id or ""),
                    "status": _STATUS_MAP.get(r.status, "Fail"),
                    "comment": r.error_message or "",
                }
                for r in results
            ],
        }
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.post(
                    f"{self._base}/rest/atm/1.0/testresult/bulk",
                    json=payload,
                    headers=self._headers,
                )
                resp.raise_for_status()
        except Exception as exc:
            raise QMetryError(f"QMetry push failed: {exc}") from exc
        return cycle_key

    async def create_test_cycle(self, name: str, service_name: str) -> str:
        payload = {
            "name": name,
            "projectKey": self._project,
            "description": f"Generated by AITA for {service_name}",
        }
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.post(
                    f"{self._base}/rest/atm/1.0/testrun",
                    json=payload,
                    headers=self._headers,
                )
                resp.raise_for_status()
                return resp.json().get("key", "")
        except Exception as exc:
            raise QMetryError(f"QMetry cycle creation failed: {exc}") from exc

    async def get_project_key(self) -> str:
        return self._project
