from enum import StrEnum


class Language(StrEnum):
    PYTHON = "python"
    JAVA = "java"
    GO = "go"
    TYPESCRIPT = "typescript"


class SpecFormat(StrEnum):
    OPENAPI_3 = "openapi3"
    SWAGGER_2 = "swagger2"
    PROTO = "proto"


class RunStatus(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class TestStatus(StrEnum):
    GENERATED = "generated"
    HEALED = "healed"
    PASSING = "passing"
    FAILING = "failing"
    SKIPPED = "skipped"
    DROPPED = "dropped"


class FeedbackSource(StrEnum):
    AUTO = "auto"       # generated by healer / executor
    QE = "qe"          # imported from QE feedback YAML
    CI = "ci"          # imported from CI failure logs


class FeedbackType(StrEnum):
    COMPILATION_ERROR = "compilation_error"
    RUNTIME_ERROR = "runtime_error"
    ASSERTION_FAILURE = "assertion_failure"
    WRONG_STATUS_CODE = "wrong_status_code"
    MISSING_FIXTURE = "missing_fixture"
    CROSS_LANG_CONTAMINATION = "cross_lang_contamination"
    HARDCODED_VALUE = "hardcoded_value"
    AUTH_PATTERN = "auth_pattern"
    CUSTOM = "custom"


class LLMProvider(StrEnum):
    ANTHROPIC = "anthropic"
    OLLAMA = "ollama"


class PipelineStep(StrEnum):
    GIT_PULL = "git_pull"
    SPEC_PARSE = "spec_parse"
    SOURCE_SCAN = "source_scan"
    ENDPOINT_DIFF = "endpoint_diff"
    RAG_ENRICH = "rag_enrich"
    FETCH_EXISTING = "fetch_existing"
    GENERATE = "generate"
    HEAL = "heal"
    PERSIST = "persist"
    EXECUTE = "execute"
    FEEDBACK = "feedback"
    REPORT = "report"
    GATE = "gate"
    PUBLISH = "publish"
